### ISSUE TITLE
Move to roxygen has removed most exports

### ISSUE THREAD

**Issue by richfitz** [hrbrmstr/RBerkeley#1]
See this commit: https://github.com/hrbrmstr/RBerkeley/commit/6f6b531df756aefd9618703cda48de60ec2c04bd

Most of the package is no longer exported and needs many more `@export` flags.

If you'd like a PR I am happy to do this.

**Comment by hrbrmstr** [comment]
Apologies for that oversight. A PR wld be great. thx.
